credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: "appetizer-github-credentials"
              password: "dbd9afe4fe1e4cc0787e698651fe1b8b22517395"
              scope: GLOBAL
              username: "WilliamLu2019"
jobs:
  - url: https://raw.githubusercontent.com/paradyme-management/appetizer-jcasc/main/folder.groovy
  - url: https://raw.githubusercontent.com/paradyme-management/appetizer-jcasc/main/jobs.groovy    

